pepfile: config/pep/config.yaml

# for testing, uncomment to limit to n strain genomes
limit-strain-genomes: 10

variant-calling:
  # false discovery rate to control for
  fdr: 0.05
  # downsample loci to this read depth
  max-read-depth: 2000
  report:
    # downsample loci to this read depth for visualization in report
    max-read-depth: 100

strain-calling:
  # minimum reported strain fraction after quantification
  min-fraction: 0.02

adapters:
  #  Illumina TruSeq adapters
  illumina: "--adapter_sequence AGATCGGAAGAGCACACGTCTGAACTCCAGTCA --adapter_sequence_r2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"